### ISSUE TITLE
Add split user resource for create/modify

### ISSUE THREAD

**Issue by oferrigni** [sensu/sensu-go-chef#33]
Feature Request:
Add user support for sensu-go-chef.

Please add support for a user creation and user modification resource. User modification should allow modification of any suer meta data (roles, etc). Delete could be a function of the user modification resource as an action.

This issue is the start of a discussion and isn't complete.

**Comment by majormoses** [comment]
To add some missing context the reason for using different custom resources for create vs modify is that if they were the same object/resource then we would need to keep track of the users password in chef which is not ideal. When creating a user their initial password will need to be specified and the recommended solution is use a library such as `securerandom` and send the password encrypted via something like keybase with their pgp key. After the fact managing the users access should not require any of their password only the admin credentials.

**Comment by webframp** [comment]
I get the reasoning here I think, but please correct me if I’m wrong. It sounds like this could be one resource with different actions. 

I think the right way to handle a user password in a custom resource is to just not do it. You can find an example of this in the sql server cookbook where formerly an install was done using a generated password and now just requires a user to set something on their own. 

It seems like we should allow the user to provide a password for a create action however they want instead of generating a random one for them. 

Still open to any discussion and ideas of course.

**Comment by majormoses** [comment]
@webframp I will hit you up via slack to coordinate a discussion around this.

**Comment by mercul3s** [comment]
I started implementing this, but I'm going to put this on the backburner as the model for RBAC in sensu-go is going to change a bit: https://github.com/sensu/sensu-go/issues/2105 This will impact the way RBAC resources are created with sensuctl.

**Comment by cwjohnston** [comment]
Auth API now supports testing user passwords, which may be helpful in determining if an existing User resource needs to be updated https://docs.sensu.io/sensu-go/latest/api/auth/#authtest-get

**Comment by calebhailey** [comment]
Not sure if it will be helpful here, but we also now support [a `password_hash` property](https://docs.sensu.io/sensu-go/latest/operations/control-access/rbac/#user-specification), and the corresponding utility in `sensuctl` to generate the password hashes: https://docs.sensu.io/sensu-go/latest/sensuctl/#generate-a-password-hash

**Comment by majormoses** [comment]
Nice, I think the `password_hash` makes it a lot safer to throw around because as I see it that hash can't directly be used outside of that context of creating/editing users and still requires an authenticated session. Let me know if I misunderstood.

Do we have the capability of modifying some user attributes without having to touch their authentication? If I was not using SSO with enterprise I think this would be the route I personally might choose to go down. Ideally we can support both use cases in the same resource by omitting those properties on `nil` or something along those lines. I think it would now be safe enough to put the admin in the drivers seat with enough docs and let them make their decision.
