### ISSUE TITLE
Chef supermarket

### ISSUE THREAD

**Issue by anthonyneto** [sensu/sensu-go-chef#45]
I see the badge on the readme however I was unable to find the supermarket location for this cookbook.

**Comment by webframp** [comment]
As far as I know this hasn’t been released to supermarket yet. 

@portertech want to discuss when that should happen?

**Comment by majormoses** [comment]
It has intentionally not been released to the supermarket to indicate that its still under heavy development and subject to changes hence why we funnel folks here. Regarding the badge, it shows as not found because its not present yet. Currently we are tagging releases in git so you can pull it there.

That being said we are gonna have to push it at some point. I need to take a closer look and see how complete it is. The outstanding items that that I can think of off the top of my head:
- how do we handle users? (ongoing discussions) I dont consider this one a blocker yet
- check hooks: should be pretty easy to implement
- SSO configurations: not really a blocker and only relevant to enterprise

**Comment by webframp** [comment]
I’d love to see these or other community concerns turned into issues here. I’m happy to dedicate time to chunk away at the stuff that’s important to the chef/Sensu community users

**Comment by majormoses** [comment]
@webframp the only one that is not in an issue or pr is SSO configurations.

**Comment by majormoses** [comment]
after #47 lands I think I could be talked into doing a supermarket release as a `0.1.0` version. I think its still missing some essential components but the main reason we held off was that a lot of the apis changed out from underneath us here, now that sensu-go apis are much more stable I'm inclined to make it more accessible.

**Comment by webframp** [comment]
definitely agree with @majormoses we should get a `0.1.0` version released to supermarket so we can make it easier for community members to consume and improve.

@portertech or @cwjohnston Do you have any time to chat or provide input on the process you want to follow for that release?

**Comment by derekgroh** [comment]
@webframp this was requested in slack today, friendly reminder if there has been any traction or to at least outline what steps are still required.

**Comment by webframp** [comment]
@majormoses What do you think about setting a target date to achieve this by? I think a lot of people would like to see this thing released in some form, even while we continue to polish the Windows support and improve resources.

**Comment by majormoses** [comment]
https://supermarket.chef.io/cookbooks/sensu-go
